name: canary

on:
  push:
    branches: [ "canary" ]

jobs:
  canary_build:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - run: go version

      - name: check gh-cli user
        run: gh auth status | grep Logged
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: download Test Resources
        run: make devr
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: download Frontend
        run: make frontend
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: run Tests
        run: make gh_test
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
          LOG_MODE: verbose
        
      - name: run Build
        run: make build

      - name: create github canary release
        run: gh release create canary-build-v${{ github.run_number }} dist.zip scheduling-system-temporary-data.zip --title "Canary Build" --notes "canary build version number ${{ github.run_number }}" --draft=false --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy to canary
        if: github.ref == 'refs/heads/canary'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"