name: tests

on:
  push:
    branches: [ "master", "main", "development", "api_test" ]
  pull_request:
    branches: [ "master", "main", "development", "api_test" ]

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [ 1.21.x ]

    permissions: 
        contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check gh-cli user
        run: gh auth status | grep Logged
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Download Test Resources
        run: make devr
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: View Temporary Data Tree
        run: tree scheduling-system-temporary-data

      - name: I
        if: runner.os == 'Linux'
        run: cat scheduling-system-temporary-data/instructors.json | sed -E 's/("FirstName":[[:space:]]*)"[^"]*"/\1"****"/g;s/("MiddleInitial":[[:space:]]*)"[^"]*"/\1"****"/g;s/("LastName":[[:space:]]*)"[^"]*"/\1"****"/g' scheduling-system-temporary-data/instructors.json

      - name: Run Tests
        run: make gh_test
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Run Benchmarks
        run: make bench

      - name: Run Build
        run: make build

      - name: Change Node Fetch Wait Value
        run: sed -i 's/1000 * 60 * 16/1000 * 60 * 4/' Tests/schedule-serialization.js

      - name: Check Node Fetch Wait Value
        run: grep -nr "1000 \* 60 \*" ./Tests

      - name: Run Server And Node Fetch Test
        run: |
            ./app & sleep 1 && node Tests/schedule-serialization.js
            make devr && ./app & sleep 1 && node Tests/schedule-serialization.js
        env:
          PORT: 3000
          GIN_MODE: debug
          PROTOCOL: tcp
          NODE_VERSION: lts
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
