name: tests

on:
  push:
    branches: [ "master", "main", "development", "api_test" ]
  pull_request:
    branches: [ "master", "main", "development", "api_test" ]

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [ 1.21.x ]

    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check gh-cli user
        run: gh auth status | grep Logged
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Download Test Resources
        run: gh release --repo github.com/mrdcvlsc/scheduling-system-temporary-data download --pattern *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: View Files
        run: ls

      - name: Extract Release
        run: |
          mkdir scheduling-system-temporary-data
          unzip release.zip -d ./scheduling-system-temporary-data

      - name: Run Tests
        run: make test

        # build test

      - name: Run Build
        run: make build

      - name: Run Server And Node Fetch Test
        run: ./app & sleep 1 && node Tests/schedule-serialization.js
        env:
          PORT: 3000
          GIN_MODE: debug
          PROTOCOL: tcp
          NODE_VERSION: lts